config/routes.rb
CropperPlugin::Application.routes.draw do
  resources :photos do
    get 'crop/', to: 'photos#crop', as: :crop
		put 'crop_picture/', to: 'photos#crop_picture', as: :crop_picture
  end
  
  

  root :to => 'photos#index'

end

app/models/photo.rb
class Photo < ActiveRecord::Base
  attr_accessible :image_content_size, :image_content_type, :image_file_name, :image_updated_at, :name, :image, :crop_x, :crop_y, :crop_w, :crop_h, :crop_style 
  
  has_attached_file :image,
	:styles => { :medium => '600x400>', :small => '180x180#', :search_results => '136x136#', :large => 'x572', :thumbnail => '50x50#', :cropped => '400x225' },
    :processors => [:cropper],
	:default_style => :medium
	
  validates_attachment_content_type :image, :content_type => /^image\/(jpg|jpeg|pjpeg|png|x-png|gif)$/, :message => 'file type is not allowed (only jpeg/png/gif images)'

  after_update :reprocess_image, :if => :cropping?
  
  attr_accessor :crop_x, :crop_y, :crop_w, :crop_h, :crop_style, :processing
  
  def cropping?
    !crop_x.blank? && !crop_y.blank? && !crop_w.blank? && !crop_h.blank? && !crop_style.blank?
  end
  
  private

  def reprocess_image
    # don't crop if the user isn't updating the photo
    #   ...or if the photo is already being processed
    return unless (cropping? && !processing)
    logger.debug "Processing cropped image"
    self.processing = true
    image.reprocess! crop_style.parameterize.underscore.to_sym
    self.processing = false
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery
end

app/controllers/photos_controller.rb
class PhotosController < ApplicationController
  # GET /photos
  # GET /photos.json
  def index
    @photos = Photo.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @photos }
    end
  end

  # GET /photos/1
  # GET /photos/1.json
  def show
    @photo = Photo.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @photo }
    end
  end

  # GET /photos/new
  # GET /photos/new.json
  def new
    @photo = Photo.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @photo }
    end
  end

  # GET /photos/1/edit
  def edit
    @photo = Photo.find(params[:id])
  end

  # POST /photos
  # POST /photos.json
  def create
    @photo = Photo.new(params[:photo])

    respond_to do |format|
      if @photo.save
        format.html { redirect_to @photo, notice: 'Photo was successfully created.' }
        format.json { render json: @photo, status: :created, location: @photo }
      else
        format.html { render action: "new" }
        format.json { render json: @photo.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /photos/1
  # PUT /photos/1.json
  def update
    @photo = Photo.find(params[:id])

    respond_to do |format|
      if @photo.update_attributes(params[:photo])
        format.html { redirect_to @photo, notice: 'Photo was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @photo.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /photos/1
  # DELETE /photos/1.json
  def destroy
    @photo = Photo.find(params[:id])
    @photo.destroy

    respond_to do |format|
      format.html { redirect_to photos_url }
      format.json { head :no_content }
    end
  end
  
  def crop
    @photo = Photo.find(params[:photo_id])
  end
	
	def crop_picture
		@photo = Photo.find(params[:photo_id])

    respond_to do |format|
      if @photo.update_attributes(params[:photo])
        format.html { redirect_to photo_crop_path(@photo), notice: 'Photo was successfully updated.' }
        format.json { head :no_content }
        format.js
      else
        logger.debug('ERRRRRORRRRRR!')
        flash[:error] = @photo.errors.full_messages
        format.html { render action: "edit" }
        format.json { render json: @photo.errors, status: :unprocessable_entity }
      end
    end
	end
  
  private

  def photo_params
    params.require(:photo).permit(:crop_x, :crop_y, :crop_w, :crop_h, :crop_style)
  end
  
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/photos_helper.rb
module PhotosHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>CropperPlugin</title>
  <%= stylesheet_link_tag    "application", :media => "all" %>
  <%= javascript_include_tag "application" %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= yield %>

</body>
</html>

app/views/photos/_form.html.erb
<%= simple_form_for(@photo, :html => { :multipart => true }) do |f| %>
  <% if @photo.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@photo.errors.count, "error") %> prohibited this photo from being saved:</h2>

      <ul>
      <% @photo.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.input :image %>
  </div>
  <div class="field">
    <%= f.label :name %><br />
    <%= f.text_field :name %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/photos/crop.html.erb
<script>
  'use strict';
    var styleHash = {
      <% @photo.image.styles.map{|style| %>
        "<%= style[0].to_s %>": "<%= raw style[1][:geometry] %>",
      <% } %>
   };
 var image_path = "<%= @photo.image.url %>";
</script>

<section id="photo_crop"> 
  <section id="photo_cropper_container">
    <h2 hidden>Photo Cropper</h2>
    <h3>Photo Crop for <%= @photo.id %></h3>
    <%= image_tag @photo.image(:original), :id => 'img_crop', :class => ('img_crop_' + @photo.id.to_s) %>
  </section>


  <section id="cropper_previews">
    <h2 hidden>Preview Windows for cropping</h2>
    <h3>Main Preview</h3>
    <div id="main_preview" class="cropper_preview">
    </div>

    <section id="current_image">
      Current Cropped Image <br />
      
      <div class="loader">
        <div class="square" ></div>
        <div class="square"></div>
        <div class="square last"></div>
        <div class="square clear"></div>
        <div class="square"></div>
        <div class="square last"></div>
        <div class="square clear"></div>
        <div class="square "></div>
        <div class="square last"></div>
      </div>


      <%= image_tag @photo.image(:original), :id => 'current_preview' %>
    </section>
  </section>

  <section id="photo_form">
    <h2 hidden>Photo form</h2>
    <%= simple_form_for @photo, remote: true, :url => photo_crop_picture_path(@photo), :html => { :onsubmit => "hidePreview()" } do |f| %>
      <%= f.input :crop_x  %>
      <%= f.input :crop_y  %>
      <%= f.input :crop_h  %>
      <%= f.input :crop_w  %>
      <%= f.input :crop_style, :collection => f.object.image.styles.map{|style| style[0].to_s }, :input_html => { :value => 'medium' }  %>
      <%= f.submit 'Crop Photo' %>
    <% end %>
  </section>
</section>


app/views/photos/crop_picture.js.erb
'use strict';
var currentImage = $('#current_preview');
currentImage.prop("src", (currentImage.prop("src").replace(/\?.*/g, ""))+ '?' + Math.random());
setTimeout(showPreview, 10000);

app/views/photos/edit.html.erb
<h1>Editing photo</h1>

<%= render 'form' %>

<%= link_to 'Show', @photo %> |
<%= link_to 'Back', photos_path %>

app/views/photos/index.html.erb
<h1>Listing photos</h1>

<table>
  <tr>
    <th>Image thumb</th>
    <th>Image content type</th>
    <th>Image content size</th>
    <th>Image file name</th>
    <th>Image updated at</th>
    <th>Name</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @photos.each do |photo| %>
  <tr>
    <td><%= image_tag photo.image.url(:thumbnail) %></td>
    <td><%= photo.image_content_type %></td>
    <td><%= photo.image_file_size %></td>
    <td><%= photo.image_file_name %></td>
    <td><%= photo.image_updated_at %></td>
    <td><%= photo.name %></td>
    <td><%= link_to 'Show', photo %></td>
    <td><%= link_to 'Edit', edit_photo_path(photo) %></td>
    <td><%= link_to 'Crop', photo_crop_path(photo) %></td>
    <td><%= link_to 'Destroy', photo, method: :delete, data: { confirm: 'Are you sure?' } %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New Photo', new_photo_path %>

app/views/photos/new.html.erb
<h1>New photo</h1>

<%= render 'form' %>

<%= link_to 'Back', photos_path %>

app/views/photos/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <%= image_tag(@photo.image.url) %>
</p>

<p>
  <b>Image content type:</b>
  <%= @photo.image_content_type %>
</p>
<p>
  <b>Image content size:</b>
  <%= @photo.image_file_size %>
</p>

<p>
  <b>Image file name:</b>
  <%= @photo.image_file_name %>
</p>

<p>
  <b>Image updated at:</b>
  <%= @photo.image_updated_at %>
</p>

<p>
  <b>Name:</b>
  <%= @photo.name %>
</p>


<%= link_to 'Edit', edit_photo_path(@photo) %> |
<%= link_to 'Back', photos_path %>